; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino

; 1. 시리얼 모니터 통신 속도 설정
monitor_speed = 921600

; 2. 컴파일러 빌드 최적화 옵션
build_flags = -O3